### ISSUE TITLE
Why don't add relu in inference network?

### ISSUE THREAD

**Issue by XiaotianM** [jiny2001/deeply-recursive-cnn-tf#6]
In paper<Deeply-Recursive Convolutional Network for Image Super-Resolution>, we find the authors use conv+relu in inference Network. Due to: 

> The recurrence relation is Hd = g(Hd−1) = max(0; W ∗ Hd−1 + b), Inference net f2 is equivalent to the composition of the same elementary function g: f2(H) = (g ◦ g ◦ · · · ◦)g(H) = gD(H)

But in your code, you have not use relu in the inference Network.
Your code: (the 200th-201th line in super_resolution.py file)
```
for i in range(0, self.inference_depth):
      self.H_conv[i+1] = util.conv2d_with_bias(self.H_conv[i], self.W_conv, 1, self.B_conv, name="H%d"%(i+1))

```
I think need to change like this:
```
for i in range(0, self.inference_depth):
      self.H_conv[i+1] = util.conv2d_with_bias(self.H_conv[i], self.W_conv, 1, self.B_conv, add_relu=True, name="H%d"%(i+1))
```

Is this a mistake? The reason you can't the achieve the performance like authors?
Looking forward to your reply

**Comment by XiaotianM** [comment]
And in reconstruction Network, Why do relu operation related with residual Net?
```
      self.Y1_conv[i] = util.conv2d_with_bias(self.H_conv[i], self.WD1_conv, self.cnn_stride, self.BD1_conv, add_relu=not self.residual, name="Y%d_1"%i)
      self.Y2_conv[i] = util.conv2d_with_bias(self.Y1_conv[i], self.WD2_conv, self.cnn_stride, self.BD2_conv, add_relu=not self.residual, name="Y%d_2"%i)
```

Does residul means skip connetion?

**Comment by jiny2001** [comment]
Hi XiaotianM,

Thank you to point it out.
I'm not sure why I didn't add relu for inference net.

I believe originally I added relu. But later I replaced and refactored with util.conv2d_with_bias() and I might miss to put "add_relu=True" at that time.

You can add "add_relu=True". I will try with the modification later and will upload result and weights with that. For reconstruction Network, residual is an experimental option. Usually it's off so you will use relu for reconstruction.

Residual Network (ResNet) is from Microsoft Research. And It's very effective. :)

**Comment by XiaotianM** [comment]
Thanks for your reply.

Although residual is off, I can use relu in reconstruction,
However, the authors use the skip connection in his experiment, isn't it?
 
`if self.residual:
      self.y_ = self.y_ + self.x`

So, I think whether ResNet is used, self.y_ need to equal self.y_ + self.x
I am not sure.

**Comment by jiny2001** [comment]
Hi I don't think self.y_ need to equal self.y_ + self.x.

Residual is used to let the model learn the diff of output. 
(Usually implemented with adding the input signal)
Skip connection (in this paper) is used to send a local (input image) features to the reconstruction net.
(Usually implemented with concatenating the input signal)

Actually, the same author of the DRCN proposed another SR model with using residual net at almost same time. (VDSR in CVPR 2016)

BTW, the point is, I'm also not sure about skip connection in their paper.
I implemented their model following their paper and Figure3. In this figure, (a) and (c) is different because there is no skip connection in (c). And if you look at skip connection in (a), I'm not sure what does input signal do.

In my understanding about the paper, I should concatenate input signal to every H1 to HD outputs and then put each output into reconstruction net. However, I was not 100% sure. So I implemented skip connection as like my code. Put input image to embed net and then just send it to reconstruction net. 

I welcome you to think about it and modify my code.

Jin

**Comment by XiaotianM** [comment]
Hi, jin

     I see. Your reply is really useful for me to comprehend this work. Thank you.

     So the flag of residual in your code is used to implement (a) and (c) respectively? 
     But I am still confused why we don't need relu operation in reconstruction phase when we adopt the residual option.

     Can you explain it?

Xiaotian

**Comment by jiny2001** [comment]
I was just trying to implement residual for DRCN. 
(a) is using skip connection. Residual was not included in the paper.  But I believed residual would be effective, so I experimentally just add the structure to that paper to see what will happen.

And for reconstruction net, when you use relu, it means every outputs are >=0.
However, it must allow the outputs which is less than 0 on the last layer. So I just took relu off.

Of course you can add relu and check the result. :)

**Comment by XiaotianM** [comment]
Thanks, you are really nice.
In fact, in that paper Figure 1. The authors add the relu in reconstruction.

Because I have no gpu recently, so I have troubled you so much.
 And I will try, thanks.

**Comment by jiny2001** [comment]
Yes, because they don't use residual. It means every output would be >= 0 in their paper, so the last relu would be good. 

BTW, thank you to let me know the bug (not adding relu on inference layers).
I will fix it and check the result later.

**Comment by XiaotianM** [comment]
Emmmm, I think we have different comprehend for skip connection.

1. I think skip connection is just send input image to the reconstruction net.
Just the bold line in Figure3 (a)

In paper,
> Now input image is directly fed into the reconstruction net
whenever it is used during recursions. Our skip-connection
has two advantages. First, network capacity to store the
input signal during recursions is saved. Second, the exact
copy of input signal can be used during target prediction

and I think the skip connection is the residual net you mean.

2.  Sending local  features to the reconstruction net may called Recursive-Supervision

**Comment by jiny2001** [comment]
No, adding the signal can be change the layer's output value.
But if you concatenate(skip connection), they can "store the input signal" and "the exact
copy of input signal can be used".
Also the authors know about residual well, so they would call it residual when they used it.

I'm not sure about Recursive-Supervision what you're calling, but "Recursive" usually means applying same filter recursively?

**Comment by XiaotianM** [comment]
Yeah, you are right. Thank you for patient explanation.
This issue can be closed.
And I expect your new results with relu in Inference  Net.

**Comment by jiny2001** [comment]
Thanks!

Now I'm trying another experiment on my GPU which will take 2-3 days. I will test it and upload the result after the experiment finished. Will keep open this issue until that. thx! ;)

**Comment by jiny2001** [comment]
Hi,
I got these results.

with normal yang91 dataset, 
36.59 32.36 31.30 without relu
36.61 32.30 31.29 with rerlu

with yang91 x4 augmented dataset, 
36.86 32.51 31.43 without relu
36.94 32.58 31.48 with relu

Results are for set5, set14, bsd100 datasets.
With small training dataset there are no difference, but with larger dataset it looks relu makes a better result. Result PSNR fluctuates because of it uses random values on their training, however, I fill there is a good difference.

I uploaded the new weights. Thank you so much, XiaotianM!
Later I will try with deeper model.

Jin
